### PR TITLE
directly use the community managed get-starknet lib

### PR DESCRIPTION
**Pull request by avimak**
Starknet is a multi-wallet env.
`@argent/get-starknet` nowadays is just a non-community managed wrapper for  `get-starknet`, the community-managed dapp<->wallet connect lib, supported (and hosted) by starkware.

### CODE REVIEW

**Comment by avimak** [comment]
@Darlington02 tnx, and pls consider to change it also in your medium post.

**Comment by Darlington02** [comment]
Yeap i will do that tonight. Thank you @avimak

**Comment by avimak** [comment]
tnx @Darlington02.

a few comments:

the link to `get-starknet` actually takes the user to argent's get-starknet wrapper instead of to the community npm package (which is https://www.npmjs.com/package/get-starknet)

image

the import should be -
```
import { connect } from "get-starknet"
```
instead of -
image


good luck 👍

**Comment by Darlington02** [comment]
Thanks. I've resolved it👍

**Pull request merged**
